spring.application.name=SubscriptionManager

# --- CONEXIÓN A BASE DE DATOS LOCAL ---
# Asegúrate de que el puerto (5432) y el nombre de la DB coincidan
spring.datasource.url=jdbc:postgresql://localhost:5432/subscription_db

# Tu usuario (por defecto suele ser postgres)
spring.datasource.username=postgres

# ¡AQUÍ VA TU CONTRASEÑA! (La que te pide pgAdmin)
spring.datasource.password=123456

# --- CONFIGURACIÓN DE JPA (HIBERNATE) ---
# "update": Crea las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
# IMPORTANTE: Esto le permite a Hibernate crear/actualizar tablas
# Opcional: Para ver el SQL en la consola (útil para aprender)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#security
spring.security.user.name=admin
spring.security.user.password=1234